### Ingestão

Importar os dados da planilha Excel usando a ferramenta pandas

In [ ]:
import sys

sys.path.append('..')

from ingestion import load_data_from_excel_sheets

data = load_data_from_excel_sheets('../../data/dados_importacao.xlsx')

In [4]:
data.head()

,Nome/Razão Social,Nome Fantasia,CPF/CNPJ,Data Nasc.,Data Cadastro cliente,Celulares,Telefones,Emails,Endereço,Número,Complemento,Bairro,CEP,Cidade,UF,Plano,Plano Valor,Vencimento,Status,Isento
0,Nicolas Melo,NaN,591.267.843-19,1982-03-16,2023-01-02,NaN,5.581004e+12,antonio65@da.br,Rua Trinta e Dois,82,"quadra 75,lote 5",Nazare,31422909,Almeida,Paraná,50MB_PLA_ITA_FIBRA_99_NOVO,99.9,15,Velocidade Reduzida,NaN
1,Igor Silveira,NaN,102.694.758-85,1975-04-26,2022-10-25,5.571677e+12,NaN,larissa73@ramos.net,Avenida Vereador Pereira Neto,107,LT 25 QD79,Gameleira,19390-846,Almeida,Paraíba,50MB_PLA_ITA_FIBRA_99_NOVO,99.9,5,Velocidade Reduzida,NaN
2,Henrique da Luz,NaN,782.531.904-41,1997-06-17,2022-10-11,5.511484e+12,5.531980e+12,aliciada-luz@goncalves.net,Rua Trinta,652,lote 18 quadra 45,Caiçaras,40016-447,Almeida,Tocantins,50MB_PLA_ITA_FIBRA_99_NOVO,99.9,15,Velocidade Reduzida,NaN
3,Valentina da Mota,NaN,865.902.374-92,NaT,2022-09-07,5.571144e+12,5.571606e+12,ramoslavinia@uol.com.br,Rua Brígida Moreira da Silva,448,lote 08,Bairro Das Indústrias Ii,01751-993,Almeida,São Paulo,300MB_PLANO_ITA_F_139_NOVO,139.9,25,Ativo,NaN
4,Giovanna Cavalcanti,NaN,173.598.642-91,1964-11-30,2023-02-13,5.541340e+12,5.531483e+12,jesusemanuelly@hotmail.com,Rua Onze,4,Lote 31 Quadra bx,Carlos Prates,39850-715,Almeidaa,Piauí,100MB_FIBRA_ITA_119_NOVO,119.9,15,Velocidade Reduzida,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nome/Razão Social      1200 non-null   object
 1   Nome Fantasia          1 non-null      object
 2   CPF/CNPJ               1200 non-null   object
 3   Data Nasc.             721 non-null    datetime64[ns]
 4   Data Cadastro cliente  1200 non-null   datetime64[ns]
 5   Celulares              1065 non-null   float64
 6   Telefones              752 non-null    float64
 7   Emails                 1167 non-null   object
 8   Endereço               1198 non-null   object
 9   Número                 1200 non-null   object
 10  Complemento            1125 non-null   object
 11  Bairro                 1200 non-null   object
 12  CEP                    1199 non-null   object
 13  Cidade                 1200 non-null   object
 14  UF                     1200 non-null   object
 15  Plano                  1200 non-null   object
 16  Plano Valor            1200 non-null   float64
 17  Vencimento             1200 non-null   int64
 18  Status                 1200 non-null   object
 19  Isento                 6 non-null      object
dtypes: datetime64[ns](2), float64(3), int64(1), object(14)
memory usage: 187.6+ KB